name: CICD Pipeline

on: [push]

jobs:
  pre-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Node.js setup
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Pre-check
        run: echo "Running pre-checks..."

  build:
    runs-on: ubuntu-latest
    needs: pre-check
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Node.js setup
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Node.js setup
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Node.js setup
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies 
        run: npm install

      - name: Test
        run: npm run test
